name: TEST NPOI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  RUN-WINDOWS-TESTS:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    
    - name: ADD msbuild TO PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: SETUP .NET 6
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 6.0.x
    
    - name: RESTORE NPOI.Multitarget.Test DEPENDENCIES
      run: dotnet restore solution/NPOI.Multitarget.Test.sln
      
    - name: BUILD NPOI.Multitarget.Test
      id: build-npoi
      run: dotnet build solution/NPOI.Multitarget.Test.sln --no-restore --configuration 'Debug' --verbosity q
      
    - name: VSTEST
      if: always() && steps.build-npoi.outcome == 'success'
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: NPOI.TestCases.dll
        searchFolder: ./testcases/main/bin/Debug/net6.0/
        runSettingsFile: ./testcases/test.core.runsettings
  
    - name: PUBLISH TEST RESULTS
      uses: dorny/test-reporter@v1
      if: always() && steps.build-npoi.outcome == 'success'
      with:
        path: 'test-results/*.trx'
        name: NPOI .NET 6 Windows Test Results
        reporter: 'dotnet-trx'
